version: '2'
services:
    db:
        image: mongo:3.0.2
        ports:
            - "27017:27017"
    web:
        build: .
        command: npm start
        ports:
            - "80:3000"
        links:
            - db
